services:
  nginx:
    image: nginx:latest
    container_name: nginx-container-lfi
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - php
  php:
    image: php:fpm
    container_name: php-container-lfi
    volumes:
      - ./app:/var/www/html
    ports:
      - 9000:9000
    